### ISSUE TITLE
Duplicate building key

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/mc-objects-and-arrays#6]
https://github.com/foundersandcoders/mc-objects-and-arrays/blob/5bf1ba1c17a0a09903cfa496f6e7a63054df8db1/tests.js#L22-L32

The test data contains a duplicate key (I assume deliberately?). This is kind of confusing for people who actually read the test at the beginning, because they keep getting an array of 4 values when they use `Object.keys`, but the object they're looking at has length 5. Unless they read the long number keys closely and realise two are identical, _and_ know that JS will overwrite previous identical keys, they'll be a bit stuck.

@eliascodes was this deliberate?

**Comment by eliasmalik** [comment]
Seems like a mistake, it's duplicated in the comments of the index.js too.

**Comment by oliverjam** [comment]
Thanks, I'll just get rid of it then
